### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by SGTGunner** [Anrop/Anrop-Arma3Sync-Manager#15]
@Dahlgren Is there any information that you can share how this works? Such as a sequence diagram, etc?
I am wanting to get general mods from withSix and then use Arma3sync to push them from a local repo?

Thanks in Advance.

--Gunner

**Comment by Dahlgren** [comment]
Added a README to the repository

**Comment by Dahlgren** [comment]
Here's a screenshot from our repository manager. "Sadly" all mods are up to date so there are no update buttons :P

![screencapture-arma3sync-anrop-se-manager-1493191876366](https://cloud.githubusercontent.com/assets/288631/25422994/4336fe20-2a63-11e7-844c-4127bc5d5b12.png)

**Comment by SGTGunner** [comment]
@Dahlgren Very cool! Dude, this is exactly what I am looking for. I happy to use and contribute back too.
