### ISSUE TITLE
Feature request: Cancel button when downloading a mod from PwS network

### ISSUE THREAD

**Issue by SGTGunner** [Anrop/Anrop-Arma3Sync-Manager#21]
@Dahlgren Using the current version of Arma3Sync manager, there is no cancel button after the download button is pressed. 

Meaning, that if you accidentally select a mod to download that is of considerable size and realize that you don't need it. 

Currently, the behavior is to wait for it to finish downloading and then delete the mod. 

This issue is a feature request for a cancel button when downloading a mod.

Thanks.

**Comment by Dahlgren** [comment]
Dahlgren/node-playwithsix/issues/24

**Comment by Dahlgren** [comment]
Underlying library needs support for canceling an active download for this to be possible.

Should any care be given to a partially downloaded mod? Mark it as incomplete? Add a button to finish?

**Comment by SGTGunner** [comment]
Does the underlying library provide that level of support? I know that you can do that with the PwS sync client. But I am not sure if that is functionality coming from their client or from the backend. That is question?

**Comment by Dahlgren** [comment]
Not currently, the node library I've created takes a list of mods to download, adds any dependencies needed and waits for it to finish downloading. The manager does not use any of the official withSIX tools.

**Comment by Dahlgren** [comment]
withSIX support removed
